name: BuildImage
on:
  workflow_dispatch:

jobs:
  lint:
    name: LintDockerFile
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: lint-docker-file
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile